---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  name: eureka-exporter-account

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eureka-exporter-role
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eureka-exporter-rolebinding
subjects:
  - kind: ServiceAccount
    name: eureka-exporter-account
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eureka-exporter-role
  apiGroup: rbac.authorization.k8s.io

### Service and Deployment
---
