---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

### RBAC
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eureka-exporter-role
rules:
  - apiGroups: ["*"]
    resources: ["services"]
    verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eureka-exporter-rolebinding
subjects:
  - kind: ServiceAccount
    name: eureka-exporter-account
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: eureka-exporter-role
  apiGroup: rbac.authorization.k8s.io

### ServiceAccount, Service and Deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eureka-exporter-account
  namespace: monitoring

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-exporter
  namespace: monitoring
  labels:
    app: eureka-exporter
    subject: eureka-exporter
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      name: prometheus
      nodePort: 31000
  selector:
    app: eureka-exporter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: eureka-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-exporter
        subject: eureka-exporter
    spec:
      serviceAccountName: eureka-exporter-account
      containers:
        - name: eureka-exporter
          image: localhost:5000/eureka_exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: prometheus
