# Service discovery
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${eureka-host:eureka-service.prod}:${eureka-port:8761}/eureka/"
  instance:
    metadata-map:
      prometheusURI: "/actuator/prometheus"

# Metrics related configurations
management.endpoints.web.exposure.include: health,info,prometheus
