---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-service
  namespace: prod
  labels:
    app: cloud-config-service
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: config
  selector:
    app: cloud-config-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-service
  namespace: prod
spec:
  selector:
    matchLabels:
      app: cloud-config-service
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-config-service
    spec:
      containers:
        - name: cloud-config-service
          image: 0xfff/demo_cloud_config_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              name: config
