---
apiVersion: v1
kind: Pod
metadata:
  name: console
  namespace: prod
spec:
  containers:
    - image: busybox
      command:
        - tail
        - -f
        - /dev/null
      imagePullPolicy: IfNotPresent
      name: busybox
