---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: prod
  labels:
    app: eureka-service
spec:
  ports:
    - protocol: TCP
      port: 8761
      targetPort: eureka-service
  selector:
    app: eureka-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  namespace: prod
spec:
  selector:
    matchLabels:
      app: eureka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: 0xfff/demo_eureka_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
              name: eureka-service
