---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moto-service
  namespace: prod
spec:
  selector:
    matchLabels:
      app: moto-service
  replicas: 1
  template:
    metadata:
      labels:
        app: moto-service
    spec:
      containers:
        - name: moto-service
          image: 0xfff/demo_moto_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: rest
          env:
            - name: CONFIG_HOST
              value: cloud-config-service.prod
