---
apiVersion: v1
kind: Service
metadata:
  name: auto-service
  namespace: prod
  labels:
    app: auto-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: rest
  selector:
    app: auto-service

---
apiVersion: v1
kind: Service
metadata:
  name: moto-service
  namespace: prod
  labels:
    app: moto-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: rest
  selector:
    app: moto-service
